[package]
name = "leave-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
leave-protocol = { path = "../leave-protocol", version = "0.1.0-alpha.1" }
prost.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
axum.workspace = true
leave-crypto = { path = "../leave-crypto", version = "0.1.0-alpha.1" }
leave-relay = { path = "../../apps/relay", version = "0.1.0-alpha.1" }
leave-protocol = { path = "../leave-protocol", version = "0.1.0-alpha.1" }
reqwest.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
